import { useState, useEffect } from "react";

/**
 * ContentAutopilotPanel — Level 2 (ACT)
 *
 * Shows content drafts generated by A14, lets user trigger generation,
 * mark drafts as published, and open them in WP editor.
 */
export default function ContentAutopilotPanel({ dark, clientId, getToken, API }) {
  const bg   = dark ? "#111"    : "#ffffff";
  const bg2  = dark ? "#1a1a1a" : "#f8f8f4";
  const bdr  = dark ? "#222"    : "#e0e0d8";
  const txt  = dark ? "#e8e8e8" : "#1a1a18";
  const txt2 = dark ? "#888"    : "#666";

  const [drafts,    setDrafts]    = useState([]);
  const [running,   setRunning]   = useState(false);
  const [loading,   setLoading]   = useState(true);
  const [error,     setError]     = useState("");
  const [success,   setSuccess]   = useState("");
  const [maxArts,   setMaxArts]   = useState(3);
  const [expanded,  setExpanded]  = useState(null);

  async function loadDrafts() {
    setLoading(true);
    try {
      const token = await getToken();
      const res   = await fetch(`${API}/api/agents/${clientId}/content-drafts`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      setDrafts(data.drafts || []);
    } catch { /* silent */ }
    setLoading(false);
  }

  useEffect(() => { loadDrafts(); }, [clientId]);

  async function runAutopilot() {
    setRunning(true);
    setError("");
    setSuccess("");
    try {
      const token = await getToken();
      const res   = await fetch(`${API}/api/agents/${clientId}/run-a14`, {
        method:  "POST",
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body:    JSON.stringify({ maxArticles: maxArts }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to run content autopilot");
      setSuccess(`Generated ${data.articlesCreated || 0} article draft(s) — ready for review in WordPress`);
      await loadDrafts();
    } catch (e) {
      setError(e.message);
    }
    setRunning(false);
  }

  async function markPublished(draftId) {
    try {
      const token = await getToken();
      const res   = await fetch(`${API}/api/agents/${clientId}/content-drafts/${draftId}/publish`, {
        method:  "POST",
        headers: { Authorization: `Bearer ${token}` },
      });
      if (!res.ok) throw new Error("Failed to mark as published");
      await loadDrafts();
    } catch (e) { setError(e.message); }
  }

  const pending   = drafts.filter(d => d.status === "draft");
  const published = drafts.filter(d => d.status === "published");

  return (
    <div style={{ marginTop: 16 }}>
      {/* Header */}
      <div style={{ display:"flex", alignItems:"center", justifyContent:"space-between", marginBottom:16, flexWrap:"wrap", gap:10 }}>
        <div>
          <div style={{ fontSize:17, fontWeight:800, color:txt }}>📝 Content Autopilot</div>
          <div style={{ fontSize:12, color:txt2, marginTop:3 }}>
            AI scans your keyword gaps, writes full SEO articles and pushes them to WordPress as drafts for your review.
          </div>
        </div>
        <div style={{ display:"flex", alignItems:"center", gap:8 }}>
          <select
            value={maxArts}
            onChange={e => setMaxArts(Number(e.target.value))}
            style={{ padding:"6px 10px", borderRadius:8, border:`1px solid ${bdr}`, background:bg2, color:txt, fontSize:12 }}>
            {[1,2,3,5,10].map(n => <option key={n} value={n}>{n} article{n>1?"s":""}</option>)}
          </select>
          <button
            onClick={runAutopilot}
            disabled={running}
            style={{ padding:"8px 18px", borderRadius:8, background: running ? "#666" : "#443DCB", color:"#fff", fontWeight:700, fontSize:13, cursor: running ? "not-allowed" : "pointer", border:"none" }}>
            {running ? "⏳ Generating..." : "⚡ Generate Articles"}
          </button>
        </div>
      </div>

      {/* Messages */}
      {error   && <div style={{ padding:"10px 14px", borderRadius:8, background:"#DC262611", border:"1px solid #DC262633", color:"#DC2626", fontSize:13, marginBottom:12 }}>{error}</div>}
      {success && <div style={{ padding:"10px 14px", borderRadius:8, background:"#05966911", border:"1px solid #05966933", color:"#059669", fontSize:13, marginBottom:12 }}>{success}</div>}

      {/* How it works */}
      <div style={{ padding:"14px 18px", borderRadius:10, background:"#443DCB11", border:"1px solid #443DCB33", marginBottom:20 }}>
        <div style={{ fontSize:12, fontWeight:700, color:"#6B62E8", marginBottom:8 }}>How Content Autopilot Works</div>
        <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fit, minmax(180px,1fr))", gap:8 }}>
          {[
            { step:"1", label:"Gap Detection", desc:"Finds high-priority keywords with no matching page on your WP site" },
            { step:"2", label:"AI Writing", desc:"Writes full SEO-optimised articles with title, body, meta & slug" },
            { step:"3", label:"WP Push", desc:"Pushes each article to WordPress as a draft — your editor reviews before publishing" },
            { step:"4", label:"Track & Learn", desc:"When you publish, AI records it to avoid duplicate topics in future runs" },
          ].map(s => (
            <div key={s.step} style={{ padding:"10px 12px", borderRadius:8, background:bg, border:`1px solid ${bdr}` }}>
              <div style={{ fontSize:10, fontWeight:700, color:"#6B62E8", marginBottom:3 }}>STEP {s.step} · {s.label}</div>
              <div style={{ fontSize:11, color:txt2, lineHeight:1.5 }}>{s.desc}</div>
            </div>
          ))}
        </div>
      </div>

      {loading ? (
        <div style={{ textAlign:"center", padding:"32px 0", color:txt2, fontSize:13 }}>Loading drafts…</div>
      ) : (
        <>
          {/* Pending Drafts */}
          <div style={{ marginBottom:24 }}>
            <div style={{ fontSize:13, fontWeight:700, color:txt, marginBottom:10 }}>
              Waiting for Review
              <span style={{ marginLeft:8, padding:"2px 8px", borderRadius:10, background:"#D9770622", color:"#D97706", fontSize:11 }}>{pending.length}</span>
            </div>

            {pending.length === 0 ? (
              <div style={{ padding:"20px", borderRadius:10, background:bg2, border:`1px dashed ${bdr}`, textAlign:"center", color:txt2, fontSize:12 }}>
                No pending drafts. Click "Generate Articles" to create AI-written content from your keyword gaps.
              </div>
            ) : (
              <div style={{ display:"flex", flexDirection:"column", gap:10 }}>
                {pending.map(d => (
                  <DraftCard
                    key={d.id} draft={d} bg={bg} bg2={bg2} bdr={bdr} txt={txt} txt2={txt2}
                    expanded={expanded === d.id}
                    onToggle={() => setExpanded(expanded === d.id ? null : d.id)}
                    onMarkPublished={() => markPublished(d.id)}
                  />
                ))}
              </div>
            )}
          </div>

          {/* Published */}
          {published.length > 0 && (
            <div>
              <div style={{ fontSize:13, fontWeight:700, color:txt, marginBottom:10 }}>
                Published
                <span style={{ marginLeft:8, padding:"2px 8px", borderRadius:10, background:"#05966922", color:"#059669", fontSize:11 }}>{published.length}</span>
              </div>
              <div style={{ display:"flex", flexDirection:"column", gap:8 }}>
                {published.map(d => (
                  <div key={d.id} style={{ padding:"12px 16px", borderRadius:10, background:bg2, border:`1px solid ${bdr}`, display:"flex", alignItems:"center", justifyContent:"space-between", flexWrap:"wrap", gap:8 }}>
                    <div>
                      <div style={{ fontSize:13, fontWeight:600, color:txt }}>{d.title || d.keyword}</div>
                      <div style={{ fontSize:11, color:txt2, marginTop:3 }}>
                        Published {d.publishedAt ? new Date(d.publishedAt).toLocaleDateString() : "—"}
                        {d.keyword && ` · Target: ${d.keyword}`}
                      </div>
                    </div>
                    <div style={{ display:"flex", gap:6 }}>
                      {d.wpPostUrl && (
                        <a href={d.wpPostUrl} target="_blank" rel="noopener noreferrer"
                          style={{ padding:"5px 12px", borderRadius:6, background:"transparent", border:`1px solid ${bdr}`, color:txt2, fontSize:12, textDecoration:"none" }}>
                          View Post ↗
                        </a>
                      )}
                      <span style={{ padding:"5px 12px", borderRadius:6, background:"#05966922", color:"#059669", fontSize:12 }}>✅ Published</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}

function DraftCard({ draft, bg, bg2, bdr, txt, txt2, expanded, onToggle, onMarkPublished }) {
  const wordCount = draft.content ? draft.content.split(/\s+/).length : 0;

  return (
    <div style={{ borderRadius:10, background:bg2, border:`1px solid ${bdr}`, overflow:"hidden" }}>
      {/* Card Header */}
      <div
        style={{ padding:"14px 16px", cursor:"pointer", display:"flex", alignItems:"center", justifyContent:"space-between", gap:10 }}
        onClick={onToggle}>
        <div style={{ flex:1, minWidth:0 }}>
          <div style={{ fontSize:14, fontWeight:700, color:txt, marginBottom:3, overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" }}>
            {draft.title || draft.keyword || "Untitled Draft"}
          </div>
          <div style={{ fontSize:11, color:txt2, display:"flex", gap:10, flexWrap:"wrap" }}>
            {draft.keyword && <span>🎯 {draft.keyword}</span>}
            {wordCount > 0 && <span>📝 {wordCount} words</span>}
            {draft.metaDescription && <span>✅ Meta desc</span>}
            {draft.schema && <span>✅ Schema</span>}
            {draft.wpPostId && <span>🔗 WP #{draft.wpPostId}</span>}
            <span style={{ color: draft.createdAt ? "#888" : "transparent" }}>
              {draft.createdAt ? new Date(draft.createdAt).toLocaleDateString() : ""}
            </span>
          </div>
        </div>
        <div style={{ display:"flex", alignItems:"center", gap:8, flexShrink:0 }}>
          {draft.wpEditUrl && (
            <a href={draft.wpEditUrl} target="_blank" rel="noopener noreferrer"
              onClick={e => e.stopPropagation()}
              style={{ padding:"5px 12px", borderRadius:6, background:"#443DCB22", border:"1px solid #443DCB44", color:"#6B62E8", fontSize:12, textDecoration:"none" }}>
              Edit in WP ↗
            </a>
          )}
          <button
            onClick={e => { e.stopPropagation(); onMarkPublished(); }}
            style={{ padding:"5px 12px", borderRadius:6, background:"#05966911", border:"1px solid #05966933", color:"#059669", fontSize:12, cursor:"pointer" }}>
            ✅ Mark Published
          </button>
          <span style={{ color:txt2, fontSize:12 }}>{expanded ? "▲" : "▼"}</span>
        </div>
      </div>

      {/* Expanded Content Preview */}
      {expanded && (
        <div style={{ borderTop:`1px solid ${bdr}`, padding:"16px" }}>
          {/* Meta */}
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:12, marginBottom:16 }}>
            {draft.metaDescription && (
              <div style={{ padding:"10px 12px", borderRadius:8, background:bg, border:`1px solid ${bdr}` }}>
                <div style={{ fontSize:10, fontWeight:700, color:"#6B62E8", marginBottom:4 }}>META DESCRIPTION</div>
                <div style={{ fontSize:12, color:txt, lineHeight:1.5 }}>{draft.metaDescription}</div>
              </div>
            )}
            {draft.slug && (
              <div style={{ padding:"10px 12px", borderRadius:8, background:bg, border:`1px solid ${bdr}` }}>
                <div style={{ fontSize:10, fontWeight:700, color:"#6B62E8", marginBottom:4 }}>URL SLUG</div>
                <div style={{ fontSize:12, color:txt, fontFamily:"monospace" }}>/{draft.slug}</div>
              </div>
            )}
          </div>

          {/* Content preview */}
          {draft.content && (
            <div style={{ padding:"12px 14px", borderRadius:8, background:bg, border:`1px solid ${bdr}` }}>
              <div style={{ fontSize:10, fontWeight:700, color:"#6B62E8", marginBottom:8 }}>CONTENT PREVIEW</div>
              <div style={{ fontSize:12, color:txt, lineHeight:1.7, maxHeight:300, overflowY:"auto", whiteSpace:"pre-wrap" }}>
                {draft.content.slice(0, 1500)}{draft.content.length > 1500 ? "…" : ""}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
