import { useState } from "react";

export default function ReportGenerator({ dark, keys, model, msgs }) {
  const [clientName, setClientName] = useState("");
  const [website, setWebsite]       = useState("");
  const [period, setPeriod]         = useState("March 2026");
  const [loading, setLoading]       = useState(false);
  const [report, setReport]         = useState("");
  const [step, setStep]             = useState(1);

  const bg   = dark ? "#0a0a0a" : "#f5f5f0";
  const bg2  = dark ? "#111"    : "#ffffff";
  const bg3  = dark ? "#1a1a1a" : "#f0f0ea";
  const bdr  = dark ? "#222"    : "#e0e0d8";
  const txt  = dark ? "#e8e8e8" : "#1a1a18";
  const txt2 = dark ? "#666"    : "#888";
  const txt3 = dark ? "#444"    : "#bbb";

  const totalAnalyses = Object.values(msgs).reduce((a, m) => a + Math.floor(m.length / 2), 0);
  const toolsUsed = Object.keys(msgs).filter(k => msgs[k].length > 0);

  async function generateReport() {
    const key = model === "groq" ? keys.groq : keys.gemini;
    if (!key) return;
    setLoading(true);

    const analysisContext = toolsUsed.slice(0, 5).map(toolId => {
      const toolMsgs = msgs[toolId] || [];
      if (toolMsgs.length >= 2) {
        return `Tool: ${toolId}\nQuery: ${toolMsgs[0]?.text?.slice(0,100)}\nInsight: ${toolMsgs[1]?.text?.slice(0,300)}`;
      }
      return "";
    }).filter(Boolean).join("\n\n---\n\n");

    const prompt = `You are a professional SEO consultant creating a client report. Generate a comprehensive SEO report with the following details:

Client: ${clientName || "Client"}
Website: ${website || "website.com"}
Report Period: ${period}
Total Analyses Done: ${totalAnalyses}
Tools Used: ${toolsUsed.join(", ") || "Various SEO tools"}

${analysisContext ? `Recent Analysis Context:\n${analysisContext}` : ""}

Generate a professional SEO report with these sections:
1. Executive Summary (2-3 paragraphs)
2. Key Performance Highlights (5 bullet points)
3. SEO Health Overview (score out of 100 with breakdown)
4. Top Achievements This Period (3-5 items)
5. Issues Identified (3-5 with priority)
6. Recommendations for Next Month (5 actionable items)
7. Next Steps & Action Plan (30-day plan)
8. Conclusion

Make it professional, data-driven, and client-friendly. Use specific numbers and percentages where possible.`;

    try {
      let text = "";
      if (model === "groq") {
        const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
          method: "POST",
          headers: { "Content-Type": "application/json", "Authorization": `Bearer ${key}` },
          body: JSON.stringify({ model: "llama-3.1-8b-instant", max_tokens: 2000, messages: [{ role: "user", content: prompt }] })
        });
        const d = await res.json();
        text = d.choices?.[0]?.message?.content || "";
      } else {
        const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${key}`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] })
        });
        const d = await res.json();
        text = d.candidates?.[0]?.content?.parts?.[0]?.text || "";
      }
      setReport(text);
      setStep(3);
    } catch(e) { setReport("Error: " + e.message); }
    setLoading(false);
  }

  function downloadReport() {
    const content = `SEO PERFORMANCE REPORT
${"=".repeat(60)}
Client:  ${clientName || "Client"}
Website: ${website || "website.com"}
Period:  ${period}
Generated: ${new Date().toLocaleDateString()}
${"=".repeat(60)}

${report}

${"=".repeat(60)}
Generated by SEO Agent v9.0
seo-agent-6jrv.onrender.com`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `seo-report-${(clientName || "client").toLowerCase().replace(/\s+/g, "-")}-${period.replace(/\s+/g, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function printReport() {
    const content = `
      <html><head><title>SEO Report - ${clientName}</title>
      <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; color: #333; line-height: 1.6; }
        h1 { color: #7C3AED; border-bottom: 3px solid #7C3AED; padding-bottom: 10px; }
        h2 { color: #444; margin-top: 30px; }
        .header { background: #f8f5ff; padding: 20px; border-radius: 8px; margin-bottom: 30px; }
        .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-top: 10px; }
        .meta-item { font-size: 14px; } .meta-label { color: #888; font-size: 12px; }
        pre { white-space: pre-wrap; font-family: Arial; }
        @media print { body { margin: 20px; } }
      </style></head>
      <body>
        <div class="header">
          <h1>SEO Performance Report</h1>
          <div class="meta">
            <div class="meta-item"><div class="meta-label">Client</div>${clientName || "Client"}</div>
            <div class="meta-item"><div class="meta-label">Website</div>${website || "website.com"}</div>
            <div class="meta-item"><div class="meta-label">Period</div>${period}</div>
            <div class="meta-item"><div class="meta-label">Generated</div>${new Date().toLocaleDateString()}</div>
          </div>
        </div>
        <pre>${report}</pre>
        <hr><p style="color:#888;font-size:12px;text-align:center">Generated by SEO Agent v9.0</p>
      </body></html>`;
    const win = window.open("", "_blank");
    win.document.write(content);
    win.document.close();
    win.print();
  }

  const inp = { width:"100%", padding:"10px 14px", borderRadius:10, border:`1px solid ${bdr}`, background:bg3, color:txt, fontSize:13, outline:"none", boxSizing:"border-box", fontFamily:"inherit" };
  const btn = (color, disabled) => ({ padding:"10px 20px", borderRadius:10, border:"none", background:disabled?"#333":color, color:disabled?txt3:"#fff", fontWeight:600, fontSize:13, cursor:disabled?"not-allowed":"pointer" });

  return (
    <div style={{ flex:1, overflowY:"auto", padding:24, background:bg }}>
      <div style={{ maxWidth:750, margin:"0 auto" }}>
        <div style={{ fontSize:18, fontWeight:700, color:txt, marginBottom:4 }}>📄 SEO Report Generator</div>
        <div style={{ fontSize:13, color:txt2, marginBottom:24 }}>Generate a professional client-ready SEO report in seconds</div>

        {/* Progress */}
        <div style={{ display:"flex", gap:8, marginBottom:24, alignItems:"center" }}>
          {["Client Info","Review","Report"].map((s, i) => (
            <div key={i} style={{ display:"flex", alignItems:"center", gap:8 }}>
              <div style={{ width:28, height:28, borderRadius:"50%", display:"flex", alignItems:"center", justifyContent:"center", fontSize:12, fontWeight:700, background: step>i?"#7C3AED":step===i+1?"#7C3AED22":bg3, color: step>i?"#fff":step===i+1?"#A78BFA":txt3, border:`1px solid ${step>=i+1?"#7C3AED44":bdr}` }}>
                {step>i?"✓":i+1}
              </div>
              <span style={{ fontSize:12, color:step===i+1?txt:txt3, fontWeight:step===i+1?600:400 }}>{s}</span>
              {i<2 && <div style={{ width:30, height:1, background:bdr }} />}
            </div>
          ))}
        </div>

        {/* Step 1 — Client Info */}
        {step === 1 && (
          <div style={{ background:bg2, border:`1px solid ${bdr}`, borderRadius:12, padding:24 }}>
            <div style={{ fontSize:14, fontWeight:600, color:txt, marginBottom:20 }}>Client Information</div>
            <div style={{ display:"flex", flexDirection:"column", gap:14 }}>
              <div>
                <div style={{ fontSize:12, color:txt2, marginBottom:6 }}>Client / Company Name</div>
                <input value={clientName} onChange={e=>setClientName(e.target.value)} placeholder="Damco Group" style={inp} />
              </div>
              <div>
                <div style={{ fontSize:12, color:txt2, marginBottom:6 }}>Website URL</div>
                <input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://damcogroup.com" style={inp} />
              </div>
              <div>
                <div style={{ fontSize:12, color:txt2, marginBottom:6 }}>Report Period</div>
                <input value={period} onChange={e=>setPeriod(e.target.value)} placeholder="March 2026" style={inp} />
              </div>
              <div style={{ background:bg3, borderRadius:10, padding:14 }}>
                <div style={{ fontSize:12, color:txt2, marginBottom:8 }}>Report will include data from:</div>
                <div style={{ display:"flex", flexWrap:"wrap", gap:6 }}>
                  {toolsUsed.length > 0 ? toolsUsed.map(t => (
                    <span key={t} style={{ fontSize:11, padding:"2px 8px", borderRadius:6, background:"#7C3AED22", color:"#A78BFA" }}>{t}</span>
                  )) : (
                    <span style={{ fontSize:12, color:txt3 }}>No analyses yet — run some tools first for richer reports</span>
                  )}
                </div>
              </div>
              <button onClick={()=>setStep(2)} style={btn("#7C3AED", false)}>
                Next: Review →
              </button>
            </div>
          </div>
        )}

        {/* Step 2 — Review */}
        {step === 2 && (
          <div style={{ background:bg2, border:`1px solid ${bdr}`, borderRadius:12, padding:24 }}>
            <div style={{ fontSize:14, fontWeight:600, color:txt, marginBottom:20 }}>Review & Generate</div>
            <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:12, marginBottom:20 }}>
              {[
                { label:"Client", value: clientName || "Not set" },
                { label:"Website", value: website || "Not set" },
                { label:"Period", value: period },
                { label:"Analyses", value: `${totalAnalyses} total` },
                { label:"Tools Used", value: `${toolsUsed.length} tools` },
                { label:"AI Model", value: model==="groq"?"Groq (Fast)":"Gemini (Smart)" },
              ].map(item => (
                <div key={item.label} style={{ background:bg3, borderRadius:8, padding:"10px 14px" }}>
                  <div style={{ fontSize:11, color:txt2, marginBottom:2 }}>{item.label}</div>
                  <div style={{ fontSize:13, fontWeight:500, color:txt }}>{item.value}</div>
                </div>
              ))}
            </div>
            <div style={{ display:"flex", gap:10 }}>
              <button onClick={()=>setStep(1)} style={{ ...btn(bdr, false), color:txt2 }}>← Back</button>
              <button onClick={generateReport} disabled={loading} style={{ ...btn("#7C3AED", loading), flex:1 }}>
                {loading ? "⏳ Generating Report..." : "🚀 Generate Report"}
              </button>
            </div>
          </div>
        )}

        {/* Step 3 — Report */}
        {step === 3 && report && (
          <div>
            <div style={{ background:bg2, border:`1px solid ${bdr}`, borderRadius:12, padding:24, marginBottom:16 }}>
              <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:16 }}>
                <div style={{ fontSize:14, fontWeight:600, color:txt }}>📄 Generated Report</div>
                <div style={{ display:"flex", gap:8 }}>
                  <button onClick={downloadReport} style={{ padding:"6px 14px", borderRadius:8, border:"1px solid #0F766E44", background:"#0F766E11", color:"#0F766E", fontSize:12, cursor:"pointer" }}>⬇️ Download</button>
                  <button onClick={printReport} style={{ padding:"6px 14px", borderRadius:8, border:"1px solid #7C3AED44", background:"#7C3AED11", color:"#A78BFA", fontSize:12, cursor:"pointer" }}>🖨️ Print/PDF</button>
                  <button onClick={()=>{ setStep(1); setReport(""); }} style={{ padding:"6px 14px", borderRadius:8, border:`1px solid ${bdr}`, background:"transparent", color:txt2, fontSize:12, cursor:"pointer" }}>New Report</button>
                </div>
              </div>
              <div style={{ background:bg3, borderRadius:10, padding:20 }}>
                <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:10, marginBottom:16, paddingBottom:16, borderBottom:`1px solid ${bdr}` }}>
                  <div><div style={{ fontSize:10, color:txt2 }}>CLIENT</div><div style={{ fontSize:13, fontWeight:600, color:txt }}>{clientName||"Client"}</div></div>
                  <div><div style={{ fontSize:10, color:txt2 }}>WEBSITE</div><div style={{ fontSize:13, fontWeight:600, color:txt }}>{website||"website.com"}</div></div>
                  <div><div style={{ fontSize:10, color:txt2 }}>PERIOD</div><div style={{ fontSize:13, fontWeight:600, color:txt }}>{period}</div></div>
                </div>
                <div style={{ fontSize:13, color:txt, lineHeight:1.8, whiteSpace:"pre-wrap" }}>{report}</div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}