import { useState } from "react";

export default function ReportGenerator({ dark, keys, model, msgs }) {
  const [clientName, setClientName] = useState("");
  const [website, setWebsite]       = useState("");
  const [period, setPeriod]         = useState("March 2026");
  const [loading, setLoading]       = useState(false);
  const [report, setReport]         = useState("");
  const [step, setStep]             = useState(1);
  const [pdfLoading, setPdfLoading] = useState(false);

  const bg   = dark ? "#0a0a0a" : "#f5f5f0";
  const bg2  = dark ? "#111"    : "#ffffff";
  const bg3  = dark ? "#1a1a1a" : "#f0f0ea";
  const bdr  = dark ? "#222"    : "#e0e0d8";
  const txt  = dark ? "#e8e8e8" : "#1a1a18";
  const txt2 = dark ? "#666"    : "#888";
  const txt3 = dark ? "#444"    : "#bbb";

  const totalAnalyses = Object.values(msgs).reduce((a, m) => a + Math.floor(m.length / 2), 0);
  const toolsUsed = Object.keys(msgs).filter(k => msgs[k].length > 0);

  async function generateReport() {
    const key = model === "groq" ? keys.groq : keys.gemini;
    if (!key) return;
    setLoading(true);

    const analysisContext = toolsUsed.slice(0, 5).map(toolId => {
      const toolMsgs = msgs[toolId] || [];
      if (toolMsgs.length >= 2) {
        return `Tool: ${toolId}\nQuery: ${toolMsgs[0]?.text?.slice(0,100)}\nInsight: ${toolMsgs[1]?.text?.slice(0,300)}`;
      }
      return "";
    }).filter(Boolean).join("\n\n---\n\n");

    const prompt = `You are a professional SEO consultant creating a client report. Generate a comprehensive SEO report with the following details:

Client: ${clientName || "Client"}
Website: ${website || "website.com"}
Report Period: ${period}
Total Analyses Done: ${totalAnalyses}
Tools Used: ${toolsUsed.join(", ") || "Various SEO tools"}

${analysisContext ? `Recent Analysis Context:\n${analysisContext}` : ""}

Generate a professional SEO report with these sections:
1. Executive Summary (2-3 paragraphs)
2. Key Performance Highlights (5 bullet points)
3. SEO Health Overview (score out of 100 with breakdown)
4. Top Achievements This Period (3-5 items)
5. Issues Identified (3-5 with priority)
6. Recommendations for Next Month (5 actionable items)
7. Next Steps & Action Plan (30-day plan)
8. Conclusion

Make it professional, data-driven, and client-friendly. Use specific numbers and percentages where possible.`;

    try {
      let text = "";
      if (model === "groq") {
        const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
          method: "POST",
          headers: { "Content-Type": "application/json", "Authorization": `Bearer ${key}` },
          body: JSON.stringify({ model: "llama-3.1-8b-instant", max_tokens: 4000, messages: [{ role: "user", content: prompt }] })
        });
        const d = await res.json();
        text = d.choices?.[0]?.message?.content || "";
      } else {
        const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${key}`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] })
        });
        const d = await res.json();
        text = d.candidates?.[0]?.content?.parts?.[0]?.text || "";
      }
      setReport(text);
      setStep(3);
    } catch(e) { setReport("Error: " + e.message); }
    setLoading(false);
  }

  function downloadTxt() {
    const content = `SEO PERFORMANCE REPORT\n${"=".repeat(60)}\nClient:  ${clientName || "Client"}\nWebsite: ${website || "website.com"}\nPeriod:  ${period}\nGenerated: ${new Date().toLocaleDateString()}\n${"=".repeat(60)}\n\n${report}\n\n${"=".repeat(60)}\nGenerated by SEO Agent`;
    const a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([content], { type:"text/plain" }));
    a.download = `seo-report-${(clientName||"client").toLowerCase().replace(/\s+/g,"-")}-${period.replace(/\s+/g,"-")}.txt`;
    a.click();
  }

  function exportPDF() {
    setPdfLoading(true);
    const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>SEO Report — ${clientName || "Client"}</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a18; background: #fff; padding: 0; }
    .cover { background: linear-gradient(135deg, #443DCB, #4F46E5); color: #fff; padding: 60px 50px; min-height: 280px; display: flex; flex-direction: column; justify-content: center; }
    .cover h1 { font-size: 32px; font-weight: 700; margin-bottom: 8px; }
    .cover p { font-size: 16px; opacity: 0.85; margin-bottom: 30px; }
    .cover-meta { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-top: 20px; }
    .cover-meta-item { background: rgba(255,255,255,0.15); border-radius: 8px; padding: 12px 16px; }
    .cover-meta-label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.1em; opacity: 0.7; margin-bottom: 4px; }
    .cover-meta-value { font-size: 14px; font-weight: 600; }
    .body { padding: 40px 50px; max-width: 800px; margin: 0 auto; }
    .stats-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 30px 0; }
    .stat-card { border: 1px solid #e0e0d8; border-radius: 10px; padding: 16px; text-align: center; border-top: 3px solid #443DCB; }
    .stat-num { font-size: 28px; font-weight: 700; color: #443DCB; }
    .stat-lbl { font-size: 11px; color: #888; margin-top: 4px; }
    .section { margin: 28px 0; }
    .section-title { font-size: 16px; font-weight: 700; color: #443DCB; border-bottom: 2px solid #EEEDFE; padding-bottom: 8px; margin-bottom: 14px; }
    .report-body { font-size: 13px; line-height: 1.9; color: #333; white-space: pre-wrap; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0d8; text-align: center; font-size: 11px; color: #888; }
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .cover { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      @page { margin: 0; size: A4; }
    }
  </style>
</head>
<body>
  <div class="cover">
    <h1>SEO Performance Report</h1>
    <p>Comprehensive SEO Analysis & Recommendations</p>
    <div class="cover-meta">
      <div class="cover-meta-item">
        <div class="cover-meta-label">Client</div>
        <div class="cover-meta-value">${clientName || "Client"}</div>
      </div>
      <div class="cover-meta-item">
        <div class="cover-meta-label">Website</div>
        <div class="cover-meta-value">${website || "website.com"}</div>
      </div>
      <div class="cover-meta-item">
        <div class="cover-meta-label">Report Period</div>
        <div class="cover-meta-value">${period}</div>
      </div>
      <div class="cover-meta-item">
        <div class="cover-meta-label">Generated</div>
        <div class="cover-meta-value">${new Date().toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" })}</div>
      </div>
    </div>
  </div>

  <div class="body">
    <div class="stats-grid">
      <div class="stat-card">
        <div class="stat-num">${totalAnalyses}</div>
        <div class="stat-lbl">Total Analyses</div>
      </div>
      <div class="stat-card">
        <div class="stat-num">${toolsUsed.length}</div>
        <div class="stat-lbl">Tools Used</div>
      </div>
      <div class="stat-card">
        <div class="stat-num">${new Date().getFullYear()}</div>
        <div class="stat-lbl">Report Year</div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">SEO Analysis Report</div>
      <div class="report-body">${report.replace(/</g,"&lt;").replace(/>/g,"&gt;")}</div>
    </div>

    <div class="footer">
      Generated by SEO Agent · ${new Date().toLocaleDateString()} · Confidential
    </div>
  </div>
</body>
</html>`;

    const win = window.open("", "_blank", "width=900,height=700");
    win.document.write(htmlContent);
    win.document.close();
    win.onload = () => {
      setTimeout(() => {
        win.print();
        setPdfLoading(false);
      }, 500);
    };
  }

  const inp = { width:"100%", padding:"10px 14px", borderRadius:10, border:`1px solid ${bdr}`, background:bg3, color:txt, fontSize:13, outline:"none", boxSizing:"border-box", fontFamily:"inherit" };
  const btn = (color, disabled) => ({ padding:"10px 20px", borderRadius:10, border:"none", background:disabled?"#333":color, color:disabled?txt3:"#fff", fontWeight:600, fontSize:13, cursor:disabled?"not-allowed":"pointer" });

  return (
    <div style={{ flex:1, overflowY:"auto", padding:24, background:bg }}>
      <div style={{ maxWidth:750, margin:"0 auto" }}>
        <div style={{ fontSize:18, fontWeight:700, color:txt, marginBottom:4 }}>📄 SEO Report Generator</div>
        <div style={{ fontSize:13, color:txt2, marginBottom:24 }}>Generate a professional client-ready SEO report with PDF export</div>

        {/* Progress */}
        <div style={{ display:"flex", gap:8, marginBottom:24, alignItems:"center" }}>
          {["Client Info","Review","Report"].map((s, i) => (
            <div key={i} style={{ display:"flex", alignItems:"center", gap:8 }}>
              <div style={{ width:28, height:28, borderRadius:"50%", display:"flex", alignItems:"center", justifyContent:"center", fontSize:12, fontWeight:700, background: step>i?"#443DCB":step===i+1?"#443DCB22":bg3, color: step>i?"#fff":step===i+1?"#6B62E8":txt3, border:`1px solid ${step>=i+1?"#443DCB44":bdr}` }}>
                {step>i?"✓":i+1}
              </div>
              <span style={{ fontSize:12, color:step===i+1?txt:txt3, fontWeight:step===i+1?600:400 }}>{s}</span>
              {i<2 && <div style={{ width:30, height:1, background:bdr }} />}
            </div>
          ))}
        </div>

        {/* Step 1 */}
        {step === 1 && (
          <div style={{ background:bg2, border:`1px solid ${bdr}`, borderRadius:12, padding:24 }}>
            <div style={{ fontSize:14, fontWeight:600, color:txt, marginBottom:20 }}>Client Information</div>
            <div style={{ display:"flex", flexDirection:"column", gap:14 }}>
              <div>
                <div style={{ fontSize:12, color:txt2, marginBottom:6 }}>Client / Company Name</div>
                <input value={clientName} onChange={e=>setClientName(e.target.value)} placeholder="Damco Group" style={inp} />
              </div>
              <div>
                <div style={{ fontSize:12, color:txt2, marginBottom:6 }}>Website URL</div>
                <input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://damcogroup.com" style={inp} />
              </div>
              <div>
                <div style={{ fontSize:12, color:txt2, marginBottom:6 }}>Report Period</div>
                <input value={period} onChange={e=>setPeriod(e.target.value)} placeholder="March 2026" style={inp} />
              </div>
              <div style={{ background:bg3, borderRadius:10, padding:14 }}>
                <div style={{ fontSize:12, color:txt2, marginBottom:8 }}>Report will include data from:</div>
                <div style={{ display:"flex", flexWrap:"wrap", gap:6 }}>
                  {toolsUsed.length > 0 ? toolsUsed.map(t => (
                    <span key={t} style={{ fontSize:11, padding:"2px 8px", borderRadius:6, background:"#443DCB22", color:"#6B62E8" }}>{t}</span>
                  )) : (
                    <span style={{ fontSize:12, color:txt3 }}>No analyses yet — run some tools first for richer reports</span>
                  )}
                </div>
              </div>
              <button onClick={()=>setStep(2)} style={btn("#443DCB", false)}>Next: Review →</button>
            </div>
          </div>
        )}

        {/* Step 2 */}
        {step === 2 && (
          <div style={{ background:bg2, border:`1px solid ${bdr}`, borderRadius:12, padding:24 }}>
            <div style={{ fontSize:14, fontWeight:600, color:txt, marginBottom:20 }}>Review & Generate</div>
            <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:12, marginBottom:20 }}>
              {[
                { label:"Client",   value: clientName || "Not set" },
                { label:"Website",  value: website || "Not set" },
                { label:"Period",   value: period },
                { label:"Analyses", value: `${totalAnalyses} total` },
                { label:"Tools",    value: `${toolsUsed.length} tools` },
                { label:"Model",    value: model==="groq"?"Groq (Fast)":"Gemini (Smart)" },
              ].map(item => (
                <div key={item.label} style={{ background:bg3, borderRadius:8, padding:"10px 14px" }}>
                  <div style={{ fontSize:11, color:txt2, marginBottom:2 }}>{item.label}</div>
                  <div style={{ fontSize:13, fontWeight:500, color:txt }}>{item.value}</div>
                </div>
              ))}
            </div>
            <div style={{ display:"flex", gap:10 }}>
              <button onClick={()=>setStep(1)} style={{ ...btn(bdr, false), color:txt2 }}>← Back</button>
              <button onClick={generateReport} disabled={loading} style={{ ...btn("#443DCB", loading), flex:1 }}>
                {loading ? "⏳ Generating Report..." : "🚀 Generate Report"}
              </button>
            </div>
          </div>
        )}

        {/* Step 3 */}
        {step === 3 && report && (
          <div>
            <div style={{ background:bg2, border:`1px solid ${bdr}`, borderRadius:12, padding:24, marginBottom:16 }}>
              <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:16, flexWrap:"wrap", gap:8 }}>
                <div style={{ fontSize:14, fontWeight:600, color:txt }}>📄 Generated Report</div>
                <div style={{ display:"flex", gap:8, flexWrap:"wrap" }}>
                  <button onClick={exportPDF} disabled={pdfLoading} style={{ padding:"6px 14px", borderRadius:8, border:"1px solid #443DCB44", background:"#443DCB", color:"#fff", fontSize:12, cursor:"pointer", fontWeight:600 }}>
                    {pdfLoading ? "⏳ Opening..." : "📥 Export PDF"}
                  </button>
                  <button onClick={downloadTxt} style={{ padding:"6px 14px", borderRadius:8, border:"1px solid #0F766E44", background:"#0F766E11", color:"#0F766E", fontSize:12, cursor:"pointer" }}>⬇️ Download TXT</button>
                  <button onClick={()=>{ setStep(1); setReport(""); }} style={{ padding:"6px 14px", borderRadius:8, border:`1px solid ${bdr}`, background:"transparent", color:txt2, fontSize:12, cursor:"pointer" }}>New Report</button>
                </div>
              </div>

              {/* PDF Preview Card */}
              <div style={{ background:"#443DCB", borderRadius:10, padding:"20px 24px", marginBottom:16, color:"#fff" }}>
                <div style={{ fontSize:16, fontWeight:700, marginBottom:4 }}>SEO Performance Report</div>
                <div style={{ fontSize:12, opacity:0.8, marginBottom:16 }}>Comprehensive SEO Analysis & Recommendations</div>
                <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:10 }}>
                  {[
                    { label:"CLIENT", value: clientName||"Client" },
                    { label:"WEBSITE", value: website||"website.com" },
                    { label:"PERIOD", value: period },
                    { label:"GENERATED", value: new Date().toLocaleDateString() },
                  ].map(m => (
                    <div key={m.label} style={{ background:"rgba(255,255,255,0.15)", borderRadius:6, padding:"8px 12px" }}>
                      <div style={{ fontSize:9, opacity:0.7, letterSpacing:"0.1em", marginBottom:2 }}>{m.label}</div>
                      <div style={{ fontSize:12, fontWeight:600 }}>{m.value}</div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Stats */}
              <div style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:10, marginBottom:16 }}>
                {[
                  { num: totalAnalyses, label:"Total Analyses" },
                  { num: toolsUsed.length, label:"Tools Used" },
                  { num: report.split(" ").length, label:"Words in Report" },
                ].map(s => (
                  <div key={s.label} style={{ background:bg3, border:`1px solid ${bdr}`, borderRadius:8, padding:"12px 16px", textAlign:"center", borderTop:"3px solid #443DCB" }}>
                    <div style={{ fontSize:22, fontWeight:700, color:"#443DCB" }}>{s.num}</div>
                    <div style={{ fontSize:11, color:txt2, marginTop:2 }}>{s.label}</div>
                  </div>
                ))}
              </div>

              {/* Report Body */}
              <div style={{ background:bg3, borderRadius:10, padding:20 }}>
                <div style={{ fontSize:13, color:txt, lineHeight:1.9, whiteSpace:"pre-wrap" }}>{report}</div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}